/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    YourContract2: {
      address:
        "0x03d6f0f0ca78a90dfc7a95869887c9ecb608886a45a4b297e62ba1cb9573eb8f",
      abi: [
        {
          type: "impl",
          name: "MyFirstContract",
          interface_name: "contracts::YourContract2::IMyFirstContract",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::YourContract2::IMyFirstContract",
          items: [
            {
              type: "function",
              name: "get_value",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_value",
              inputs: [
                {
                  name: "cAddress",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "eventName",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_Owner",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_cAddress",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_eventName",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::YourContract2::YourContract2::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
  },
  sepolia: {
    YourContract2: {
      address:
        "0x071e2bf7b5d22aeb38fa36ee5b09aeee33a6013e74b34290f0164826784b5944",
      abi: [
        {
          type: "impl",
          name: "MyFirstContract",
          interface_name: "contracts::YourContract2::IMyFirstContract",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::YourContract2::IMyFirstContract",
          items: [
            {
              type: "function",
              name: "get_value",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_value",
              inputs: [
                {
                  name: "cAddress",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "eventName",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_Owner",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_cAddress",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_eventName",
              inputs: [
                {
                  name: "index",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::YourContract2::YourContract2::Event",
          kind: "enum",
          variants: [],
        },
      ],
    },
  },
} as const;

export default deployedContracts;
