[package]
name = "contracts"
version = "0.2.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "=2.8.5"
openzeppelin_access = "0.19.0"
openzeppelin_upgrades = "0.19.0"
openzeppelin_token = "0.19.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[dev-dependencies]
openzeppelin_utils = "0.19.0"
snforge_std = "0.32.0"

[[target.starknet-contract]]
casm = true

[tool.fmt]
sort-module-level-items = true
